### PR TITLE
Upgrade to Elixir 1.4 and update dependencies

### PR DESCRIPTION
**Pull request by brsntus**

### CODE REVIEW

**Comment by brsntus** [comment]
There are a lot of changes in whitespace, so I suggest adding `?w=1` when reviewing this to minimize the diff

https://github.com/CodeforChemnitz/elixir-overpass/pull/1/files?w=1

**Comment by ronnyhartenstein** [comment]
Thanks for your work! We'll check it soon and merge it then.

**Comment by symptog** [comment]
```
Finished in 13.6 seconds
12 tests, 0 failures
```

:+1: should be fine to merge

**Review by symptog — APPROVED** [review]
:+1:

**Pull request merged**
